### ISSUE TITLE
[Feat] 전화번호 인증 API 로직 구현

### ISSUE THREAD

**Issue by zzammin** [pinshot/pinshot-backend#2]
## ⚒️ Issue
전화번호 인증을 위한 API 로직 구현

## 📝 To-do
- [x] SMS API 연동하기
- [x] 인증 번호 요청 API 로직 구현
- [x] 인증 번호 확인 API 로직 구현
- [x] Redis 공부한 뒤 연동

## 📂 ETC
- 인증 번호 요청 API 로직을 구현하려면 SMS API 연동이 필요함
- SMS API 찾아야 함
