### ISSUE TITLE
[Refactor] 전화번호 인증 로직을 JWT 방식으로 변경

### ISSUE THREAD

**Issue by zzammin** [pinshot/pinshot-backend#6]
## ⚒️ Issue
전화번호 인증을 위해 기존의 Redis 연동 방식에서 JWT 사용 방식으로 변경

## 📝 To-do
- [x] 인증 번호 요청 API 로직에 JWT 추가
- [x] 인증 번호 확인 API 로직에 JWT 추가
- [x] Custom Exception, JWT 관련 Config 추가

## 📂 ETC
JWT 관련 공부 필요!
